# Generated by Django 5.1.6 on 2025-02-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codecraftapp', '0003_coursetag_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_free',
        ),
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='photos/project_images/'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='icon',
            field=models.ImageField(upload_to='photos/technology_icons/'),
        ),
    ]
