# Generated by Django 5.1.6 on 2025-02-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codecraftapp', '0004_remove_course_is_free_course_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lessons',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='course',
            name='portfolio_projects',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='course',
            name='practice',
            field=models.IntegerField(default=30),
        ),
    ]
