# Generated by Django 5.1.6 on 2025-02-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codecraftapp', '0005_course_lessons_course_portfolio_projects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_program',
            field=models.TextField(default='Kurs dasturi haqida malumot'),
        ),
    ]
