# Generated by Django 5.1.6 on 2025-02-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codecraftapp', '0006_course_course_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='photos/course-results/')),
            ],
        ),
    ]
