# Generated by Django 5.1.6 on 2025-02-26 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codecraftapp', '0007_courseresults'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseResults',
        ),
    ]
