# Generated by Django 5.1.6 on 2025-02-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codecraftapp', '0010_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='video_photo',
            field=models.ImageField(default='pageVideo.jpg', upload_to='photos/courses/'),
        ),
        migrations.AddField(
            model_name='course',
            name='video_url',
            field=models.URLField(default='https://www.youtube.com/watch?v=s3EyW4UIHLo'),
        ),
    ]
