# Generated by Django 5.1.6 on 2025-02-27 15:50

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codecraftapp', '0011_course_video_photo_course_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='UZ')),
                ('question', models.CharField(max_length=500)),
            ],
        ),
    ]
