# Generated by Django 5.1.6 on 2025-02-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codecraftapp', '0012_openlesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openlesson',
            name='question',
            field=models.TextField(),
        ),
    ]
