# Generated by Django 5.1.6 on 2025-03-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codecraftapp', '0013_alter_openlesson_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='content_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='content_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
