# Generated by Django 5.1.6 on 2025-03-10 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codecraftapp', '0016_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
        migrations.CreateModel(
            name='CoursePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('type_uz', models.CharField(max_length=200, null=True)),
                ('type_ru', models.CharField(max_length=200, null=True)),
                ('type_en', models.CharField(max_length=200, null=True)),
                ('price', models.IntegerField(default=800000)),
                ('content', models.TextField()),
                ('content_uz', models.TextField(null=True)),
                ('content_ru', models.TextField(null=True)),
                ('content_en', models.TextField(null=True)),
                ('body', models.TextField()),
                ('body_uz', models.TextField(null=True)),
                ('body_ru', models.TextField(null=True)),
                ('body_en', models.TextField(null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='codecraftapp.course')),
            ],
        ),
    ]
