# Generated by Django 5.1.6 on 2025-03-11 13:17

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codecraftapp', '0018_lessontime_courseopenlessons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseopenlessons',
            name='weekday',
        ),
        migrations.RemoveField(
            model_name='courseopenlessons',
            name='weekday_en',
        ),
        migrations.RemoveField(
            model_name='courseopenlessons',
            name='weekday_ru',
        ),
        migrations.RemoveField(
            model_name='courseopenlessons',
            name='weekday_uz',
        ),
        migrations.AddField(
            model_name='courseopenlessons',
            name='weekdays',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('dushanba', 'Dushanba'), ('seshanba', 'Seshanba'), ('chorshanba', 'Chorshanba'), ('Payshanba', 'Payshanba'), ('juma', 'Juma'), ('shanba', 'Shanba'), ('yakshanba', 'Yakshanba')], default='Dushanba', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseopenlessons',
            name='weekdays_en',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('dushanba', 'Dushanba'), ('seshanba', 'Seshanba'), ('chorshanba', 'Chorshanba'), ('Payshanba', 'Payshanba'), ('juma', 'Juma'), ('shanba', 'Shanba'), ('yakshanba', 'Yakshanba')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='courseopenlessons',
            name='weekdays_ru',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('dushanba', 'Dushanba'), ('seshanba', 'Seshanba'), ('chorshanba', 'Chorshanba'), ('Payshanba', 'Payshanba'), ('juma', 'Juma'), ('shanba', 'Shanba'), ('yakshanba', 'Yakshanba')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='courseopenlessons',
            name='weekdays_uz',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('dushanba', 'Dushanba'), ('seshanba', 'Seshanba'), ('chorshanba', 'Chorshanba'), ('Payshanba', 'Payshanba'), ('juma', 'Juma'), ('shanba', 'Shanba'), ('yakshanba', 'Yakshanba')], max_length=100, null=True),
        ),
    ]
