# Generated by Django 5.1.6 on 2025-03-11 15:39

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codecraftapp', '0019_remove_courseopenlessons_weekday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseopenlessons',
            name='weekdays_en',
        ),
        migrations.RemoveField(
            model_name='courseopenlessons',
            name='weekdays_ru',
        ),
        migrations.RemoveField(
            model_name='courseopenlessons',
            name='weekdays_uz',
        ),
        migrations.AlterField(
            model_name='courseopenlessons',
            name='weekdays',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Dushanba', 'Dushanba'), ('Seshanba', 'Seshanba'), ('Chorshanba', 'Chorshanba'), ('Payshanba', 'Payshanba'), ('Juma', 'Juma'), ('Shanba', 'Shanba'), ('Yakshanba', 'Yakshanba')], max_length=100),
        ),
    ]
