# Generated by Django 5.1.6 on 2025-03-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codecraftapp', '0021_application_created_time_openlesson_created_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='openlesson',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
